import { ChangeDetectionStrategy, Component, signal } from '@angular/core'

@Component({
	selector: 'app-delete-recurring-dialog',
	template: `
    <div class="flex flex-col gap-4">
      <p class="text-sm text-muted-foreground">This action cannot be undone.</p>
      <label class="flex items-center gap-2 cursor-pointer">
        <input
          type="checkbox"
          [checked]="deleteTransactions()"
          (change)="deleteTransactions.set(!deleteTransactions())"
          class="rounded border-border"
        />
        <span class="text-sm">Also delete all transactions generated by this recurring</span>
      </label>
    </div>
  `,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DeleteRecurringDialog {
	readonly deleteTransactions = signal(false)
}
