import {
	Briefcase,
	Bus,
	Car,
	CircleDollarSign,
	Coffee,
	Dumbbell,
	Film,
	Fuel,
	Gamepad2,
	Gift,
	GraduationCap,
	HeartPulse,
	House,
	Lightbulb,
	type LucideIconData,
	Music,
	PawPrint,
	Plane,
	Repeat2,
	Shirt,
	ShoppingBasket,
	ShoppingCart,
	Tag,
	TrendingUp,
	Utensils,
	Wifi,
	Wine,
	Wrench,
} from 'lucide-angular'

export const CATEGORY_ICON_MAP: Record<string, LucideIconData> = {
	utensils: Utensils,
	coffee: Coffee,
	wine: Wine,
	'shopping-basket': ShoppingBasket,
	car: Car,
	bus: Bus,
	fuel: Fuel,
	plane: Plane,
	house: House,
	lightbulb: Lightbulb,
	wifi: Wifi,
	wrench: Wrench,
	'gamepad-2': Gamepad2,
	music: Music,
	film: Film,
	dumbbell: Dumbbell,
	briefcase: Briefcase,
	'trending-up': TrendingUp,
	'circle-dollar-sign': CircleDollarSign,
	'repeat-2': Repeat2,
	gift: Gift,
	shirt: Shirt,
	'graduation-cap': GraduationCap,
	'heart-pulse': HeartPulse,
	'paw-print': PawPrint,
	'shopping-cart': ShoppingCart,
	tag: Tag,
}

export const CATEGORY_ICON_GROUPS = [
	{
		label: 'Food',
		icons: ['utensils', 'coffee', 'wine', 'shopping-basket'],
	},
	{
		label: 'Transport',
		icons: ['car', 'bus', 'fuel', 'plane'],
	},
	{
		label: 'Home',
		icons: ['house', 'lightbulb', 'wifi', 'wrench'],
	},
	{
		label: 'Leisure',
		icons: ['gamepad-2', 'music', 'film', 'dumbbell'],
	},
	{
		label: 'Finance',
		icons: ['briefcase', 'trending-up', 'circle-dollar-sign', 'repeat-2'],
	},
	{
		label: 'Personal',
		icons: [
			'gift',
			'shirt',
			'graduation-cap',
			'heart-pulse',
			'paw-print',
		],
	},
	{
		label: 'Other',
		icons: ['shopping-cart', 'tag'],
	},
]

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICON_MAP)
